### ISSUE TITLE
Enable word timestamps for distil-large-v3

### ISSUE THREAD

**Issue by atiorh** [argmaxinc/WhisperKit#101]
@jongwook determined the `alignment_heads` for OpenAI Whisper models by manual inspection which are required for DTW-based (Accurate) word timestamps. We need to perform the same manual inspection for distil-large-v3 so word timestamps can be enabled for it. Word timestamps are required to benefit from the "Eager Mode" streaming feature: https://x.com/argmaxinc/status/1774809790595932658?s=20

**Comment by ZachNagengast** [comment]
Completed with https://huggingface.co/distil-whisper/distil-large-v3/discussions/3
