### ISSUE TITLE
Can a local model be used without requesting the Hugging Face API?

### ISSUE THREAD

**Issue by jiangdi0924** [argmaxinc/WhisperKit#126]
Is there a way to use a local model without requesting the Hugging Face API? For some reason, the user cannot access the Huggingface API.

`

let whisperKit = try await WhisperKit(
            verbose: true,
            logLevel: .debug,
            prewarm: false,
            load: false,
            download: false
        )
                
        let path = Path.home/"Documents/openai_whisper-small/"

`

Error Info

`Task <DF53BEFE-3EB6-44A7-BA0C-74E426592D16>.<2> finished with error [18,446,744,073,709,550,416] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://huggingface.co/api/models/openai/whisper-small, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <DF53BEFE-3EB6-44A7-BA0C-74E426592D16>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <DF53BEFE-3EB6-44A7-BA0C-74E426592D16>.<2>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://huggingface.co/api/models/openai/whisper-small, NSUnderlyingError=0x600000e43600 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: lo0, proxy}}, _kCFStreamErrorCodeKey=-9816}`

**Comment by jiangdi0924** [comment]
The issue might be caused by calling the HubApi. Currently, the logic for obtaining the Tokenizer for the local model seems to involve remote retrieval.
![image](https://github.com/argmaxinc/WhisperKit/assets/21988177/86388f8b-6e3e-4f42-9ec2-80b4efe81bb4)

**Comment by atiorh** [comment]
Hi @jiangdi0924 , please check out #81. This should be fixed soon.

**Comment by atiorh** [comment]
This is fixed in the 0.6.1 release ([c20943d](https://github.com/argmaxinc/WhisperKit/commit/c20943d3f5d6f64981e9eaed8a3a9c3a62124fc5)). Please reopen the issue if the problem persists.
