### ISSUE TITLE
Feature request: In example, provide delete and re-download options

### ISSUE THREAD

**Issue by pradeepb28** [argmaxinc/WhisperKit#13]
Models are taking really good time to download. If the WiFI is OFF for a second it gets struck - it would be great if the example has two more options - Delete and Retry.

**Comment by ZachNagengast** [comment]
Hi @pradeepb28 can you elaborate a bit on what retry would entail? Would that be similar to "Cancel"?

**Comment by pradeepb28** [comment]
Retry is like Cancel the current download that was struck, delete the partially downloaded model from the folder and start re-downloading. @ZachNagengast

**Comment by ZachNagengast** [comment]
Understood, that makes sense. Putting this on the roadmap, but would make a great contribution from the community if anyone reading this is interested!

**Comment by ZachNagengast** [comment]
this is more or less implemented with #54, regarding the redownload part, the example app now checks for partially downloaded models and redownloads them if it is unable to load the models, so redownloading should be much less necessary. Cancelling a download is still a needed feature though, which swift-transformers will support.
