### ISSUE TITLE
Is it possible to run turbo model on M1?

### ISSUE THREAD

**Issue by yujinqiu** [argmaxinc/WhisperKit#149]
```
    #if os(macOS)
    if deviceName.hasPrefix("arm64") {
        if Process.processor.contains("Apple M1") {
            // Disable turbo variants for M1
```
From the code, I know turbo model is disabled on M1. 
Is it possible to run turbo model on M1?  why can't we run the turbo model ?

**Comment by atiorh** [comment]
The models are JIT compiled on the first load (Core ML and WhisperKit call this phase "Specialization"). Compilation time and peak memory are prohibitively high for turbo+M1 combinations. If you do try the combination, it would be great if you documented your experience here for others.
