### ISSUE TITLE
VAD issue with English-only models

### ISSUE THREAD

**Issue by iandundas** [argmaxinc/WhisperKit#154]
v0.7.1

| Without VAD | With VAD | 
|:-----------:|:-----------:|
| ![CleanShot 2024-05-29 at 12 11 02@2x](https://github.com/argmaxinc/WhisperKit/assets/1131967/3616f9a6-e66f-4315-82b7-c0859f9776a3) | ![image](https://github.com/argmaxinc/WhisperKit/assets/1131967/71aff651-26ff-4655-9d5a-fae88203c61d) |

File used: http://172.104.253.215/ian2-mono.wav

Platform: M1 Macbook Pro, 32 GB, Sonoma 14.5

As discussed, might be related to English-only models. However, there's also this https://github.com/argmaxinc/WhisperKit/issues/150, so not sure.

**Comment by ZachNagengast** [comment]
Thanks for the report @iandundas, are you building from source or running the testflight app? We are updating the testflight app shortly with this fix https://github.com/argmaxinc/WhisperKit/compare/v0.7.0...v0.7.1

**Comment by iandundas** [comment]
This is v0.7.1 from source

**Comment by atiorh** [comment]
@iandundas I believe @ZachNagengast fixed all of #154, #152 and #151 with #155 today. Could you please verify the fix and close the issues that are fixed for you? 🙏

**Comment by atiorh** [comment]
Note that the [latest WhisperAX on TestFlight (0.3.1)](https://testflight.apple.com/join/LPVOyJZW) includes this fix.

**Comment by iandundas** [comment]
Seems to be fixed now in v0.7.2! Thanks!
