### ISSUE TITLE
Publish in CocoaPods

### ISSUE THREAD

**Issue by raida42** [argmaxinc/WhisperKit#157]
We want to use `WhisperKit` via Podfile instead of using SwiftPM.

**Comment by ZachNagengast** [comment]
Hi @raida42, take a look at @seb-sep's excellent repo https://github.com/seb-sep/whisper-kit-expo?tab=readme-ov-file#installation 

Here he is using the `cocoapods-spm` plugin to bring it in via cocoapods

`sudo gem install cocoapods-spm` 

```ruby
### START WHISPERKIT PLUGIN SCRIPT ###
plugin "cocoapods-spm"

spm_pkg "WhisperKit",
  :url => "https://github.com/argmaxinc/WhisperKit.git",
  :version => "0.6.0",
  :products => ["WhisperKit"]
### END WHISPERKIT PLUGIN SCRIPT ###
```

**Comment by raida42** [comment]
@ZachNagengast 
Thank you for sharing! Let me take a look.
