### ISSUE TITLE
Segment order regression since 10mb chunking

### ISSUE THREAD

**Issue by iandundas** [argmaxinc/WhisperKit#163]
Since https://github.com/argmaxinc/WhisperKit/pull/158 was merged, we're seeing segments being delivered in the wrong order, including in the example app.

| 8fcfadbe37 (correct before) | 25a07498 (incorrect after) | 
|:-----------:|:-----------:|
| ![image](https://github.com/argmaxinc/WhisperKit/assets/1131967/d9713e5a-ba64-498a-81cd-a35bf806fad6) | ![image](https://github.com/argmaxinc/WhisperKit/assets/1131967/c34ddcce-348f-4b16-8a03-03c2b68af13b) |

Settings:

![image](https://github.com/argmaxinc/WhisperKit/assets/1131967/0b079bec-2317-4ab7-b881-1f33baa88f72)

Sample file: http://172.104.253.215/atp-7-min-clip.m4a

### Full transcripts:
[Full correct transcript](https://github.com/argmaxinc/WhisperKit/assets/1131967/8573b694-fd25-4e8d-9e6f-3a0c60a2a1aa)
[Full incorrect transcript](https://github.com/argmaxinc/WhisperKit/assets/1131967/afba13a8-ddfc-41e8-bfc6-47ab8bb4168d)

**Comment by ZachNagengast** [comment]
Looking at this shortly, do you have any sense of what parts specifically changed between then? Might give a clue

**Comment by iandundas** [comment]
I don't have a great handle on it, it seems completely reordered and some segments are missing

For example, in the correct transcription the word "easter" occurs once:

> [WhisperKit] [Segment 115] [474.04 --> 476.70]  So, you know **Easter** just happened in.

Whilst in the bad transcription it appears four times:

![CleanShot 2024-06-13 at 12 49 36@2x](https://github.com/argmaxinc/WhisperKit/assets/1131967/3492a086-ae82-4742-bcde-cf2b2a4d9491)

**Comment by iandundas** [comment]
[good.txt](https://github.com/user-attachments/files/15835212/good.txt)
[bad.txt](https://github.com/user-attachments/files/15835214/bad.txt)
