### ISSUE TITLE
Some advice for detecting song lyrics

### ISSUE THREAD

**Issue by Mina-H-Samy** [argmaxinc/WhisperKit#165]
Thanks for all the work you guys are doing here -- this is a fantastic project!

My usecase is pretty simple and I am unsure how to apply WhisperKit to it so I hope to get some advice from the experts here.

I am writing an app that will show song lyrics and "flip the page" when you are done with a sentence or two in order to show the next page of lyrics.
What I'm trying to do is have WhisperKit detect where in the lyrics the person is, and flip the page on its own without user interaction. What would be the best way to achieve this?

I understand that WhisperKit can detect all speech, but I want to help it by showing it the text it is meant to match the speech to. 

Thanks in advance.

**Comment by atiorh** [comment]
Thanks for the note! This sounds like a very interesting use case. What is the format of your song+lyric data? My understanding is that most songs have timestamped lyric data so I am keen to understand the challenge. WhisperKit can certainly help timestamp each word in the lyrics to your audio if the original data doesn't have this metadata.

**Comment by MinaHany** [comment]
The challenge here I think, is that these songs are not the kind you'd find on Spotify. They are old songs and they can be sung in several different ways too, so I don't really have original audios of how they're supposed to sound.. What I have is the microphone listening live to the user and a bunch of strings for the songs. 
From some initial testing, I can see that WhisperKit is very good at detecting words being sung -- but it can produce results that are incorrect, hence my question whether I can restrict the words it should be listening to based on the lyrics I have.
Thank you for your help @atiorh!

**Comment by atiorh** [comment]
Understood! In that case, you can implement a custom `SuppressTokensFilter` which was added in #14 that should take the list of tokens to suppress before each transcribe call.

**Comment by Mina-H-Samy** [comment]
Thank you @atiorh I will give that a try.
