### ISSUE TITLE
Only translating last 30s or so of the audio file.

### ISSUE THREAD

**Issue by SergioEstevao** [argmaxinc/WhisperKit#172]
When using the whisper-kit cli or apps with a large file, 50 minutes of audio, it looks like the final report (.srt file) is only showing the last 30s of content transcribed. 

Is this expected, Am I'm missing a command line argument?

**Comment by ZachNagengast** [comment]
What kind of audio is it? Also could you provide the command you are using to call the cli? This may be a result of log prob errors considering the full windows to be silent, which would happen if the audio is particularly noisy. Can you try adjusting the log prop threshold and see if the results are better?

**Comment by SergioEstevao** [comment]
So I was trying to transcribe an episode from the Cautionary Tales podcast. The sound is clear for the majority of the episodes.

I was using the CLI with this command: 
`swift run whisperkit-cli transcribe --model-path "Models/whisperkit-coreml/openai_whisper-tiny" --audio-path ../transcripts/audio.mp3 --report
`

You can get the audio file from here: 

```
https://chtbl.com/track/39E17/podtrac.com/pts/redirect.mp3/pdrl.fm/18db03/traffic.omny.fm/d/clips/e73c998e-6e60-432f-8610-ae210140c5b1/c0ae8c6e-22f0-4e9b-ac1c-ae390037ac53/a4efe84f-d748-4730-98f5-b1770137cb8e/audio.mp3
```

**Comment by ZachNagengast** [comment]
Hi @SergioEstevao I'm having trouble reproducing this, can you share your the hardware and OS you're using where this error occurs?

This is the file I get running your same command with the file
[last30bug.srt.zip](https://github.com/user-attachments/files/16036308/last30bug.srt.zip)

**Comment by ZachNagengast** [comment]
I've confirmed theres something weird with the output buffer. Will have something for this shortly.
