### ISSUE TITLE
About iOS app movement by specifying "prewarm" and "load" options

### ISSUE THREAD

**Issue by universe2024** [argmaxinc/WhisperKit#181]
thank you always.

There are "prewarm" and "load" options, but what is the difference?

It will take some time after installing the app.
It will be completed immediately after restarting the app.
I thought it would take the same amount of time even if I restarted the app because it is a process that uses memory, but is that correct?

**Comment by atiorh** [comment]
Thanks! We know this is slightly confusing and we are considering ways on improving the interface but here is the TL;DR:
- Prewarm refers to loading and unloading each model once in isolation prior to any usage so they can be compiled on-device upon first load. Second load onwards, it should not trigger recompilation unless the compiled asset was somehow purged.
- Compilation takes (significantly) more memory than the model weights so doing this in series and unloading helps reduce peak memory consumption of the app
- Core ML currently does not expose a method to check whether a model is already compiled or not so we do not skip prewarm in case the model is not yet compiled or the compiled asset had been purged for whatever reason.
- If the model was already compiled, then prewarm should incur the same latency as just a redundant load call.
