### ISSUE TITLE
Loss of results

### ISSUE THREAD

**Issue by JinYu1998** [argmaxinc/WhisperKit#186]
I was using whisperkit to recognize a long audio (about 41 minutes), and I noticed that the beginning of the audio file was lost in the results. How can I solve this problem?

**Comment by atiorh** [comment]
Would you be able to share the file for us to reproduce?

**Comment by JinYu1998** [comment]
> Would you be able to share the file for us to reproduce?

Hi, this `your.mp3` file is the one I tested. 

[your.mp3](https://drive.google.com/file/d/1vjVMKcOiesCsNx-Yd5WhUdwT8ahyDcUm/view?usp=drive_link)

and the `yout.txt` is the result on my device(Mac M1).

[yout.txt](https://drive.google.com/file/d/113MZBA8_S4-IXMlhU803PLWZxRF1uthW/view?usp=drive_link)

**Comment by atiorh** [comment]
Are you using [WhisperKit-0.8.0](https://github.com/argmaxinc/WhisperKit/releases/tag/v0.8.0)? 0.8.0 is the latest release that also backs the latest version of our TestFlight app. I just used the TestFlight app on your audio file and it did not have any loss in the beginning.

**Comment by JinYu1998** [comment]
> Are you using [WhisperKit-0.8.0](https://github.com/argmaxinc/WhisperKit/releases/tag/v0.8.0)? 0.8.0 is the latest release that also backs the latest version of our TestFlight app. I just used the TestFlight app on your audio file and it did not have any loss in the beginning.

Thank you for your reply, I have solved the problem with your suggestion.
