### ISSUE TITLE
Is it possible to recognize speech as English and then translate it into other languages?

### ISSUE THREAD

**Issue by zxl777** [argmaxinc/WhisperKit#188]
The application scenario is for English podcasts, where the speech is first recognized as English and then translated into other languages, such as Chinese.

**Comment by atiorh** [comment]
Hi @zxl777! This is not a task Whisper was natively trained for. You could pursue fine-tuning Whisper to achieve this or there might be other models that natively do what you are looking for, e.g. transcribe in English with Whisper, translate to Chinese with an LLM.
