### ISSUE TITLE
resampleAudio implementation has bug when starttime and enttime is not nil

### ISSUE THREAD

**Issue by Josscii** [argmaxinc/WhisperKit#191]
should not comparing `audioFile.framePosition` with `inputFrameCount `, but something like this:

let endFrame = AVAudioFrameCount(audioFile.framePosition) + inputFrameCount

https://github.com/argmaxinc/WhisperKit/blob/c93d613c8c6fc3ec5b9d1d9da5d1f4206183c5e4/Sources/WhisperKit/Core/AudioProcessor.swift#L296-L297

**Comment by ZachNagengast** [comment]
Thanks for the report, would you be able to post the specific exception? Or whatever test code you are using to reproduce the error?

**Comment by Josscii** [comment]
just the logic is wrong, when the audioFile is seeked to startTime, which changes its framePosition, and we should read from the frameposition until it reaches the framePosition + frameCount.

**Comment by ZachNagengast** [comment]
I think I see what you mean, so we need to calculate the ending framePosition for cases where the starting framePosition is not 0, does that sound right?

**Comment by Josscii** [comment]
yes, I'm using the `loadAudio` function to load audio buffer from time1 to time2, and found that the `resampleAudio` is not entering the while loop.

**Comment by ZachNagengast** [comment]
@Josscii I've fixed some of the logic in #195, please try it out and see if it works for your use case.

**Comment by Josscii** [comment]
Thanks for your work, I checked the code, and I think it fixed the bug.
