### ISSUE TITLE
how to output in non-english language?

### ISSUE THREAD

**Issue by rk-helper** [argmaxinc/WhisperKit#196]
hey! is there any way to output in non-english language? for now it looks like I can input in any language but output is limited to only English. any way to fix that?

**Comment by ZachNagengast** [comment]
The OpenAI Whisper model intended to translate X->English or transcribe X->X where X is one of the supported languages. The model will technically output English to X if you set up the options to transcribe and use a language besides `en` but that is a "hack" and not and intended use case, just happens to work. @Vaibhavs10 did some research on this interesting fact here https://github.com/Vaibhavs10/translate-with-whisper

Here is OpenAI's blog post on Whisper https://openai.com/index/whisper/, with more info.
![image](https://github.com/user-attachments/assets/1fd3c742-d5fc-43a4-a07f-e105f8a58d43)
