### ISSUE TITLE
VAD detection uses unbounded amount of memory

### ISSUE THREAD

**Issue by finnvoor** [argmaxinc/WhisperKit#204]
When VAD chunking is enabled, long (~ >1hr) recordings will run out of memory on iOS. This is caused by enqueuing an unbounded amount of async CoreML predictions by default, which stack up and run out of memory.

This can be mitigated by setting `concurrentWorkerCount` in `DecodeOptions` to a non-zero number (we settled on 64, which limits it to ~2gb memory). I'm not sure if defaulting to unlimited concurrent workers makes sense since you can easily run out of memory.

**Comment by atiorh** [comment]
Thanks for the report @finnvoor! We profiled different default values for this and found 16 to be reaping most of the throughput benefits while keeping the peak memory bloat reasonable. The optimal value will vary across devices and input files but the marginal benefit for fine-tuning this value is not high
