### ISSUE TITLE
Output of JSON and SRT are located at both audio file path and --report-path

### ISSUE THREAD

**Issue by maxlund** [argmaxinc/WhisperKit#211]
Hi!

When transcribing with e.g. 
```
./whisperkit-cli transcribe --skip-special-tokens --report --report-path '/Users/maxlund/whisper-reports' --chunking-strategy 'vad' --model 'large-v3_turbo_954MB' --audio-path '/Users/maxlund/audio/arthur-fx2.wav' --language 'en'
```
We get a JSON and SRT file as output in both the specified `--model-path /Users/maxlund/whisper-reports`, as well as next to the source audio file, i.e. at `--audio-path '/Users/maxlund/audio/arthur-fx2.wav'`.

We would expect it to only output files at the specified `--report-path` right?

**Comment by latenitefilms** [comment]
Ummm... I can't reproduce:

<img width="1294" alt="image" src="https://github.com/user-attachments/assets/3ec1ed0b-c9d2-4178-8ecf-a5361d870b24">

**Comment by maxlund** [comment]
Yea I'm an idiot, closing this.
