### ISSUE TITLE
Not working without an internet connection

### ISSUE THREAD

**Issue by Abdulganiylawal** [argmaxinc/WhisperKit#213]

**Comment by Abdulganiylawal** [comment]
i have downloaded the model on device

**Comment by ZachNagengast** [comment]
Can you provide any error/log messages you're seeing?

**Comment by Abdulganiylawal** [comment]
Error: Model not found. Please check the model or repo name and try again.
Error: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x300170bd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=Resolved 0 endpoints in 1ms using unknown from cache, _NSURLErrorNWPathKey=unsatisfied (No network route)}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3FB8886B-5E9F-4F5A-9AD6-ECA1FE4D9554>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3FB8886B-5E9F-4F5A-9AD6-ECA1FE4D9554>.<2>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://huggingface.co/api/models/argmaxinc/whisperkit-coreml, NSErrorFailingURLKey=https://huggingface.co/api/models/argmaxinc/whisperkit-coreml, _kCFStreamErrorDomainKey=1}

**Comment by atiorh** [comment]
Is this from the `WhisperAX` app we distribute on TestFlight or in your own project where you depend on WhisperKit as a package?

**Comment by Abdulganiylawal** [comment]
depend in it as a package

**Comment by ZachNagengast** [comment]
If you're using it locally, you need to pass a `modelFolder` into the init function, otherwise it will attempt to download the model based on its name. Here is the relevant code: https://github.com/argmaxinc/WhisperKit/blob/c2f1b57266bee2deeeac1d7014e1c05bcd32119a/Sources/WhisperKit/Core/WhisperKit.swift#L251

```swift
let localPipeline = try await WhisperKit(modelFolder: "path/to/your/model/openai_whisper-tiny")
```

**Comment by Abdulganiylawal** [comment]
It is working now thanks.

**Comment by lemo366** [comment]
` let localPipeline = try await WhisperKit(modelFolder: "path/to/your/model/openai_whisper-tiny")`

Finally, I can use the local model downloaded after connecting to the internet. After downloading once, I can do without an internet connection, thank you！
