### ISSUE TITLE
loadModels takes too much time on first startup

### ISSUE THREAD

**Issue by peng2219** [argmaxinc/WhisperKit#221]
Hi，loadModels takes too much time on first startup. I could choose a smaller model，but Is there any way to optimize it If I want to continue using a larger model?  Thanks

Here is some information,  it's only loading time without downloading.

1. Macbook Pro ｜ Apple M2 ｜ macOS Sequoia 15.0.1 ｜ 16G 
Loaded models for whisper size: large-v3 in 25.66s

2. iPhone 16 ｜ 18.0 
Loaded models for whisper size: large-v3 in 148.82s

**Comment by atiorh** [comment]
Hi @peng2219 , as few questions:
- Are you using our [TestFlight app](https://testflight.apple.com/join/LPVOyJZW)?
- Could you point to which exact model version you are using from this [list](https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main)?

**Comment by peng2219** [comment]
> Hi @peng2219 , a few questions:
> 
> * Are you using our [TestFlight app](https://testflight.apple.com/join/LPVOyJZW)?
> * Could you point to which exact model version you are using from this [list](https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main)?

Thanks for your reply @atiorh.
I am using openai_whisper-large-v3-v20240930_turbo_632MB.
I am not using WhisperKit's TestFlight app. Most of the codes to setup whisperkit and load models are from 
[TranscribeCLI.swift](https://github.com/argmaxinc/WhisperKit/blob/main/Sources/WhisperKitCLI/TranscribeCLI.swift). I have downloaded all model files and tokenizer files,  just load them from local.
Thanks for your support again.

**Comment by atiorh** [comment]
Thanks for the details @peng2219. We will be beta testing a feature that significantly speeds up loading the models in the TestFlight app next week. In the interim, you can use the same models without the "turbo" optimizations that should load faster but are slightly slower to run:
- [openai_whisper-large-v3-v20240930_626MB](https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main/openai_whisper-large-v3-v20240930_626MB)
- [openai_whisper-large-v3-v20240930_547MB](https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main/openai_whisper-large-v3-v20240930_547MB)

**Comment by peng2219** [comment]
> Thanks for the details @peng2219. We will be beta testing a feature that significantly speeds up loading the models in the TestFlight app next week. In the interim, you can use the same models without the "turbo" optimizations that should load faster but are slightly slower to run:
> 
> * [openai_whisper-large-v3-v20240930_626MB](https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main/openai_whisper-large-v3-v20240930_626MB)
> * [openai_whisper-large-v3-v20240930_547MB](https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main/openai_whisper-large-v3-v20240930_547MB)

Ok, I'll try. very glad there will be new feature to speed up loading models. Thanks.
