### ISSUE TITLE
mp3 (attached) results in "Failed to process audio buffer" issue

### ISSUE THREAD

**Issue by iandundas** [argmaxinc/WhisperKit#228]
Hi all, 

This mp3 file seems to trip WhisperKit (and latest Testflight WhisperAX on macOS)  up, just wanted to let you know :) 

I haven't dived much further though

mp3 file: https://f001.backblazeb2.com/file/sah-saus-cer/Audio-724631629-WzJBD5.mp3

<details><summary>WhisperAX log:</summary>
<p>

The "nudge" command has been installed, type "help nudge" for detailed help.
NSBundle file:///System/Library/PrivateFrameworks/MetalTools.framework/ principal class is nil because all fallbacks have failed
Found locally: ["openai_whisper-tiny", "openai_whisper-tiny.en", "openai_whisper-base", "openai_whisper-small", "openai_whisper-small.en", "distil-whisper_distil-large-v3", "distil-whisper_distil-large-v3_594MB"]
Previously selected model: openai_whisper-small
AddInstanceForFactory: No factory registered for id <CFUUID 0x600003559680> F8BB1C28-BAE8-11D6-9C31-00039315CD46
      HALC_ShellObject.mm:615    HALC_ShellObject::SetPropertyData: call to the proxy failed, Error: 1852797029 (nope)
Picker: the selection "USB PnP Audio Device" is invalid and does not have an associated tag, this will give undefined results.
Selected Model: openai_whisper-small
    Computing Options:
    - Mel Spectrogram:  cpuAndGPU
    - Audio Encoder:    cpuAndNeuralEngine
    - Text Decoder:     cpuAndNeuralEngine
    - Prefill Data:     cpuOnly
CoreSVG has logged an error. Set environment variabe "CORESVG_VERBOSE" to learn more.
Loading models from /Users/ian/Library/Containers/com.argmax.whisperkit.WhisperAXN8N37QWHHP/Data/Documents/huggingface/models/argmaxinc/whisperkit-coreml/openai_whisper-small with prewarmMode: true
Loading feature extractor
Loaded feature extractor
Loading text decoder
Loaded text decoder in 0.33s
Loading audio encoder
Loaded audio encoder in 0.25s
Loading models from /Users/ian/Library/Containers/com.argmax.whisperkit.WhisperAXN8N37QWHHP/Data/Documents/huggingface/models/argmaxinc/whisperkit-coreml/openai_whisper-small with prewarmMode: false
Loading feature extractor
Loaded feature extractor
Loading text decoder
Loaded text decoder in 0.08s
Loading audio encoder
Loaded audio encoder in 0.31s
Loading tokenizer for small
Loading tokenizer from local folder
Loaded tokenizer in 0.31s
Loaded models for whisper size: small in 1.32s
File saved to temporary directory: file:///Users/ian/Library/Containers/com.argmax.whisperkit.WhisperAXN8N37QWHHP/Data/tmp/903802B6-C330-4522-BDC6-143E33F048F9.mp3
Loading audio file: /Users/ian/Downloads/Audio 724631629.mp3
Resampling 600.00 seconds of audio
Resampling 0.00s - 30.00s
Resampling 30.00s - 60.00s
Resampling 60.00s - 90.00s
Resampling 90.00s - 120.00s
Resampling 120.00s - 150.00s
Resampling 150.00s - 180.00s
Resampling 180.00s - 210.00s
Resampling 210.00s - 240.00s
Resampling 240.00s - 270.00s
Resampling 270.00s - 300.00s
Resampling 300.00s - 330.00s
Resampling 330.00s - 360.00s
Resampling 360.00s - 390.00s
Resampling 390.00s - 420.00s
Resampling 420.00s - 450.00s
Resampling 450.00s - 480.00s
Resampling 480.00s - 510.00s
Resampling 510.00s - 540.00s
Resampling 540.00s - 570.00s
Resampling 570.00s - 600.00s
Audio source details - Sample Rate: 44100.0 Hz, Channel Count: 1, Frame Length: 32379840, Duration: 734.2367346938776s
Audio buffer details - Sample Rate: 16000.0 Hz, Channel Count: 1, Frame Length: 9600000, Duration: 600.0s
After loadAudio function - Memory usage: 302 MB
Resampling 134.24 seconds of audio
Resampling 600.00s - 630.00s
Resampling 630.00s - 660.00s
Resampling 660.00s - 690.00s
Resampling 690.00s - 720.00s
Resampling 720.00s - 734.24s
Rounding buffer frame capacity from 227369.79591836734 to 227370.0 to better fit new sample rate
Resampling 734.21s - 734.24s
Error reading audio file: nilError
Failed to process audio buffer
File selection error: Failed to process audio buffer

</p>
</details>

**Comment by atiorh** [comment]
Reproduced, thanks for the report @iandundas! Triaging

**Comment by ZachNagengast** [comment]
This is a pretty strange bug, according to AVAudioFile length property the frame length is `32379840`, however the actual frame length is `32378159`. In any case, the main issue is the fact that its trying to resample audio that it claims to have already resampled
`Resampling 720.00s - 734.24s`
vs
`Resampling 734.21s - 734.24s`
Looking into it, thanks for the report 👍
