### ISSUE TITLE
Memory leak when using ModelComputeOptions `.cpuAndGPU` with Turbo model on m1

### ISSUE THREAD

**Issue by damian0815** [argmaxinc/WhisperKit#265]
In order to get Turbo models working on base M1 devices we are passing a custom `ModelComputeOptions` struct with all options set to `.cpuAndGPU`. 

On macOS 14.6, we notice a memory leak when repeatedly destroying and re-instantiating WhisperKit over multiple iterations:

iteration 0:
<img width="1006" alt="Screenshot 2024-11-25 at 19 08 58" src="https://github.com/user-attachments/assets/18cb664a-de4f-4302-92a2-519204636132">

iteration 1:
<img width="1026" alt="Screenshot 2024-11-25 at 19 09 20" src="https://github.com/user-attachments/assets/f57ba7bb-06af-4c3d-98fa-32de6d8722c1">

iteration 2:
<img width="1016" alt="Screenshot 2024-11-25 at 19 09 43" src="https://github.com/user-attachments/assets/717e75f5-46d2-4df7-8a2b-ce58d8da6ef0">

iteration 3:
<img width="1015" alt="Screenshot 2024-11-25 at 19 10 06" src="https://github.com/user-attachments/assets/a1ab4c17-c826-473c-80f5-a10b9ff37fc4">
...

iteration 9:
<img width="1007" alt="Screenshot 2024-11-25 at 19 12 03" src="https://github.com/user-attachments/assets/c92ebd00-d641-4ca1-b354-58ed8425c740">

I'll post the code to reproduce this below.

We understand that the Turbo models are "unsupported" on baseline M1 devices (eg `Macmini9`), but we are able to work around this as demonstrated by using the model with `.cpuAndGPU` only. This leak makes things tricky for us, however. Is this a known issue? Is there any way we can avoid it?

**Comment by damian0815** [comment]
Code to reproduce the above:

run with args `--input /path/to/audio/file --output /path/to/output.srt --model /path/to/WhisperKit/Models/whisperkit-coreml/distil-whisper_distil-large-v3_turbo`

//
//  main.swift
//  WhisperKitEval
//
//  Created by Damian Stewart on 05/11/2024.
//

import Foundation
import ArgumentParser
import WhisperKit
import SwiftSubtitles

struct Arguments: ParsableArguments {
    
    @Option(name: .shortAndLong, help: "/path/to/input.{wav,mp3,m4a,flac}")
    var input: String
    
    @Option(name: .shortAndLong, help: "/path/to/output.srt")
    var output: String
    
    @Option(name: .shortAndLong, help: "/path/to/whisper/model/folder")
    var model: String
}

func writeSRT(transcriptionOutput: TranscriptionResult, outputURL: URL) throws {

    let cues = transcriptionOutput.allWords.enumerated().map { (index, word) in
        return Subtitles.Cue(position: index, startTimeInSeconds: Double(word.start), endTimeInSeconds: Double(word.end), text: word.word)
    }
    
    let subtitles = Subtitles(cues)
    let data = try Subtitles.encode(subtitles, fileExtension: "srt")
    try data.write(to: outputURL, atomically: true, encoding: .utf8)
}


@main
struct Transcriber {


    static func main() async throws {
        
        let options = Arguments.parseOrExit()
        print("input: '\(options.input)'")
        print("output: '\(options.output)'")

        // Initialize WhisperKit with default settings
        func makeTranscriptionTask() -> Task<[TranscriptionResult], any Error> {
            return Task {
                print("loading pipeline...")
                print("* using M1 compatible turbo options (all .cpuAndGPU)")
                let modelComputeOptions = ModelComputeOptions(melCompute: .cpuAndGPU,
                                                              audioEncoderCompute: .cpuAndGPU,
                                                              textDecoderCompute: .cpuAndGPU,
                                                              prefillCompute: .cpuAndGPU)
                let config = WhisperKitConfig(
                    modelFolder: options.model,
                    computeOptions: modelComputeOptions,
                    verbose: true,
                    logLevel: .debug
                )
                let pipe = try await WhisperKit(config)
                print("pipeline loaded, now transcribing...")
                let decodingOptions = DecodingOptions(wordTimestamps: true)
                let transcription = try await pipe.transcribe(audioPath: options.input,
                                                              decodeOptions: decodingOptions)
                return transcription
            }
        }

        
        for i in 0..<100 {
            print("loop iteration \(i)")
            do {
                if let transcription = try await makeTranscriptionTask().value.first {
                    print(transcription)
                    try writeSRT(transcriptionOutput: transcription, outputURL: URL(filePath: options.output))
                    print("wrote to \(options.output)")
                } else {
                    print("no transcriptions returned")
                }
                try await Task.sleep(for: .seconds(10))
            } catch {
                print("caught exception: \(error)")
            }
        }
    }
}

```

**Comment by vade** [comment]
Also, it should be noted that it appears that M1 systems on macOS 15 do not appear to have the leak, so im not sure if this is an issue with MPS framework or CoreML runtime calling MPS on older OS'es??

**Comment by atiorh** [comment]
(I assumed @damian0815 and @vade are reporting from the same project but please let me know if otherwise)

**Comment by vade** [comment]
Hey, thanks for the feedback. Yes we are colleagues, good guess :)

I'm curious your advice given the diversity of: Hardware, OS, software configs and models, how to best utilize WhisperKit.

1. We are shipping (in beta) WhisperKit across macOS M series devices and need consistent and accurate word level timestamps. We found in our testing on the type of content we are running that Distill Large V3 Turbo performs the best buy far.   During our testing though, we noticed some difference in various models accuracy when changing the compute config (ie ANE vs GPU). Is this to be expected? 

2. We run our own models alongside WhisperKit, and expect long running analysis processing to be the norm. I read somewhere that the whisper kit configs are optimized for efficiency and not necessarily performance. Do you have suggestions for highest performance configs? If we can pin our models to ANE, is there a set of models that across the M1 -> M4 devices that run faster on GPU if we dont care much about efficiency?

Thanks for all the awesome work on WhisperKit, it feels best in class by a mile. Much obliged!

**Comment by atiorh** [comment]
> I'm curious your advice given the diversity of: Hardware, OS, software configs and models, how to best utilize WhisperKit.

- Our globally recommended config is the default config: ANE for both models and VAD chunking for parallelization. This is the primary testing target for us (quality and performance testing). We can justify triaging issues and fixing them quickly if you use this default config.
- We don't recommend GPU unless you want slightly faster results on top-end Macs or you need to support a device pre-ANE (e.g. pre-2018 iPhone, Intel Mac).
- A12 and A13 are challenging: Only use tiny
- A14 and M1 chips are aligned in arch: Only use non-turbo
- A15+ and M2+ chips: Good for all models
- iOS and iPadOS: Don't use uncompressed large models

What is your intended device support?

**Comment by atiorh** [comment]
> We are shipping (in beta) WhisperKit across macOS M series devices and need consistent and accurate word level timestamps. We found in our testing on the type of content we are running that Distill Large V3 Turbo performs the best buy far. During our testing though, we noticed some difference in various models accuracy when changing the compute config (ie ANE vs GPU). Is this to be expected?

- My answer to variance is [here](https://github.com/argmaxinc/WhisperKit/issues/260#issuecomment-2471872747).
- All the quality results we published on [Whisperkit Benchmarks](https://huggingface.co/spaces/argmaxinc/whisperkit-benchmarks) is from the default ANE-only + VAD config. GPU is not supposed lead to overall quality/accuracy difference but it is not explicitly tested and verified on all supported devices like ANE is.

**Comment by atiorh** [comment]
> We run our own models alongside WhisperKit, and expect long running analysis processing to be the norm. I read somewhere that the whisper kit configs are optimized for efficiency and not necessarily performance. Do you have suggestions for highest performance configs? If we can pin our models to ANE, is there a set of models that across the M1 -> M4 devices that run faster on GPU if we dont care much about efficiency?

- Could you help me understand the distinction between efficiency and performance?
- WhisperKit is designed for max-perf and max-quality and we go after improvements that don't make a trade-off.

**Comment by vade** [comment]
Hey @atiorh thanks for the detailed reponses!

>What is your intended device support?

Desktop Macintosh systems only for now, possible iPad Pro down the line. All Apple Silicon, no x86_64 for our use cases that involve WhisperKit.

>Could you help me understand the distinction between efficiency and performance?

Basically perf per watt, ie perhaps maxing the GPU provides better performance (latency) but at the cost of more heat / wattage and for some devices would be a bad decision (ie mobile) but for plugged in, always on dedicated systems (M series macs in our case) with a custom fan setting dedicated to media analysis, perhaps not a bad choice (if GPU was in fact faster). Thats more or less my framing if that is helpful.

One follow up question if you don't mind. 

Should we expect variance in Large V3 Distill Turbo vs Large V3 Distill? (I ask because of your advice to ship non turbo on M1 vs other systems). I saw your linked comment on Variance, thank you for that, so i suppose the answer should be "yes", but to be frank im having a difficult time qualifying what 20% relative word error rate variance "looks like" and the difference in output strikes me as *very* large, so much so its a bit surprising. 

Would it be helpful for us to document some failure modes we see with the Large V3 models on different devices on the standard configs for our use cases? 

Thanks for taking the time to answer our questions, and again thank you for WhisperKit!

**Comment by atiorh** [comment]
> Would it be helpful for us to document some failure modes we see with the Large V3 models on different devices on the standard configs for our use cases?
Yes totally! Especially simple to reproduce with a sample audio file on our TestFlight.

**Comment by atiorh** [comment]
> Basically perf per watt, ie perhaps maxing the GPU provides better performance (latency) but at the cost of more heat / wattage and for some devices would be a bad decision (ie mobile) but for plugged in, always on dedicated systems (M series macs in our case) with a custom fan setting dedicated to media analysis, perhaps not a bad choice (if GPU was in fact faster). Thats more or less my framing if that is helpful.

The distinction is clear now, thanks! This all makes sense, especially for Max and Ultra chips. You previously mentioned that other models will be running concurrently with WhisperKit. I presume those models would also contend for GPU resources? If so, dispatching to ANE would keep your GPU unoccupied for your non-WhisperKit inference workloads?

**Comment by vade** [comment]
We've been trying to leverage the ANE as well, and run FP 16 and some (somewhat) optimized architectures, so we have pretty good ANE Perf as it stands. My longer term goal is to maximize apple silicon device usage (we leverage IOSurface backed video decode to ANE/CoreML and video encoders, and GPU for pre conforming video frames, and WhisperKit is being fed the audio decoded CMSampleBuffers - thus my other comments in other threads). 

If WhisperKit could be setup (model and config) to make better use of GPU and get higher perf (ie latency for inference) I can happily configure our video models to run on ANE. If the opposite is true, we can find wins for pushing WhisperKit to ANE and our models to GPU. 

My goal is to basically get 100 video decode, encode, GPU saturation and ANE usage concurrently if possible haha and im not precious about what goes where, just that compute go brrr and stuff happens as fast as possible ha  :)

Thanks again!
