### ISSUE TITLE
Issues with Transcribing Chinese Audio Using openai_whisper-large-v3-v20240930_turbo_632MB Model

### ISSUE THREAD

**Issue by ppcfan** [argmaxinc/WhisperKit#285]
I am using the openai_whisper-large-v3-v20240930_turbo_632MB model to transcribe Chinese audio, but I encountered an issue. When I set enablePromptPrefill=true and configure streamOptions.promptTokens as whisperKit.tokenizer?.encode(text: "这是一段中文文本。"), the model fails to transcribe any text. However, using the same settings with the openai_whisper-small model works fine, producing Chinese text with punctuation.

With the openai_whisper-large-v3-v20240930_turbo_632MB model, if I set enablePromptPrefill=false, the transcription works but lacks punctuation. I also tried using streamOptions.prefixTokens = whisperKit.tokenizer?.encode(text: "。这是一个句子。"), but punctuation still did not appear.

Is there any hope of resolving this issue? How can I prompt the model to include punctuation in Chinese transcriptions?

Thanks for any help!

**Comment by atiorh** [comment]
Related to #167. Especially if the error is model version dependent, then it is highly likely to be related to the fact that prompt adherence is not robust in any Whisper model version, and it may or may not work. Furthermore, the prompting feature in WhisperKit should not behave differently given that it is using the same code path across different model versions. This also points to the lack of robustness of this native model feature.
