### ISSUE TITLE
Using locally saved models

### ISSUE THREAD

**Issue by iSapozhnik** [argmaxinc/WhisperKit#46]
Hey! Thanks for making WhisperKit!

I hope I did not miss it in the documentation. But is it possible to provide a local URL to the model for the WhisperKit instead of relying on its internal mechanism to load the model? Inside my app I already have a nice UI that allows to download, suspend, and cancel download progress so would be nice if I could then feed WhisperKit with the local URL.

If there is no such functionality but you are considering adding it - I might try to help by making a PR.

Thanks.

**Comment by ZachNagengast** [comment]
Yep pretty simple to do, all that's needed is to provide a `modelFolder` when initializing the WhisperKit object and it'll use that as the path to look for the models.

```
let whisperkit = try await WhisperKit(modelFolder: "your/local/model/folder/")
```

**Comment by iSapozhnik** [comment]
Thanks a lot 👍🏻

**Comment by tymon42** [comment]
Can I import model folder when I put the folder in my project,  like:

```
private(set) var modelFolder: String = "./whisperModels"
```

Should I use absolute path or relative path?

Hmm... I'm new to Swift , sorry.
