### ISSUE TITLE
please add ipad mode

### ISSUE THREAD

**Issue by chminsc** [argmaxinc/WhisperKit#60]
would be great

**Comment by atiorh** [comment]
Hi @chminsc, what do you mean by iPad mode? Do you mean a different UI for the sample app? (WhisperAX)

**Comment by atiorh** [comment]
(WhisperKit should work on iPad without any changes)

**Comment by chminsc** [comment]
> (WhisperKit should work on iPad without any changes)

yes, it works on iPad. But would be great if it supports native iPad UI, and some useful functions like splitview and multitasking on iPad.

**Comment by ZachNagengast** [comment]
@chminsc I've pushed an update to allow the example app to run in iPad mode, please try it out and lmk if it fixes your issue 🙏

**Comment by chminsc** [comment]
> @chminsc I've pushed an update to allow the example app to run in iPad mode, please try it out and lmk if it fixes your issue 🙏 

thanks！but i dont have xcode yet, will wait for the official TestFlight app to be updated. Which haven't yet

**Comment by chminsc** [comment]
@ZachNagengast Works perfect! And it also supplies multitasking mode. thanks!

**Comment by ZachNagengast** [comment]
Glad to hear that!
