### ISSUE TITLE
Index out of range error in TextDecoder

### ISSUE THREAD

**Issue by cgfarmer4** [argmaxinc/WhisperKit#63]
Occasionally Im seeing an `index out of range` crash on the `segmentLogProbs[index]` after a long period of silence.  https://github.com/argmaxinc/WhisperKit/blob/main/Sources/WhisperKit/Core/TextDecoder.swift#L518-L521

`Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range`

Two ways I could see guarding against this:
1. [Use swift zip](https://developer.apple.com/documentation/swift/zip(_:_:))
2. Check the index against `segmentLogProbs` count. 

```
for (token, logProb) in zip(segmentTokens, segmentLogProbs) {
    tokenProbs.append([token: logProb])
}

for (index, token) in segmentTokens.enumerated() {
  if index < segmentLogProbs.count {
      tokenProbs.append([token: segmentLogProbs[index]])
  }
}
```
        
Happy to PR either one but unsure if Im missing a reason for this being as is.

**Comment by atiorh** [comment]
Thanks @cgfarmer4, are you able to share an audio file to reproduces this? It sounds like the root cause could be a bug and we might need to dig deeper

**Comment by cgfarmer4** [comment]
I unfortunately dont have an audio file as the crash has been happening while streaming. I can record the audio in my app so Ill do that for a bit when testing to see if I can reproduce this again.

**Comment by cgfarmer4** [comment]
<img width="638" alt="image" src="https://github.com/argmaxinc/WhisperKit/assets/336449/c79f7c90-176e-4b1c-a8a1-fc43a7b09a09">

Stack trace. My `AudioModifier` class has equivalent to the functions to the ones used in the `ContentView`.

**Comment by ZachNagengast** [comment]
@cgfarmer4 Are you able to check the sizes of the variables when there is a crash? I suspect segmentTokens.count is 0 when there is silence, but segmentLogProbs is always initialized with at least 1 value. Will look into this further, thanks for the report.

**Comment by ZachNagengast** [comment]
Pushed a change to fix this now, please confirm if it resolves the crashes 🙏

**Comment by cgfarmer4** [comment]
Appears resolved on my side. Thanks for the quick fix!

**Comment by cgfarmer4** [comment]
Been able to reproduce this twice in the last week on latest `main`. Both times while using streaming and the new distil models but im not sure thats related.

<img width="1724" alt="Screenshot 2024-03-29 at 8 47 46 PM" src="https://github.com/argmaxinc/WhisperKit/assets/336449/07f98302-a372-4e82-89b5-9748f6a8712f">

<img width="1726" alt="Screenshot 2024-03-26 at 8 21 00 PM" src="https://github.com/argmaxinc/WhisperKit/assets/336449/a7c6e6dc-d20c-4ba0-9962-0b2ef7cbeae0">

**Comment by ZachNagengast** [comment]
@cgfarmer4 In the latest release https://github.com/argmaxinc/WhisperKit/releases/tag/v0.5.0 there is some new logic that should keep the tokens and log probs from getting out of sync anymore, if you see the issue again on `main` please let us know. https://github.com/argmaxinc/WhisperKit/blob/b2fd48d75bc0595ec2e4b9c99d76b9a276e8dd02/Sources/WhisperKit/Core/TextDecoder.swift#L583-L585

**Comment by cgfarmer4** [comment]
Awesome @ZachNagengast! Ill close this again and reopen with any new reports. Cheers
