### ISSUE TITLE
Any way to use with iOS 15 minimum target?

### ISSUE THREAD

**Issue by dennislysenko** [argmaxinc/WhisperKit#64]
Hey guys, great work on the project and nice job with the word level timestamps recently! 

Noticed that the package says the minimum target was recently changed to iOS 16 per https://github.com/argmaxinc/WhisperKit/blob/main/Package.swift, which is great.

What would be involved in bringing this down to iOS 15?

**Comment by atiorh** [comment]
Thanks @dennislysenko! We are highly unlikely to support iOS15 as we don't have a robust way of testing such support. I also anticipate significant regressions on inference performance on iOS15 compared to 16 and 17.

**Comment by atiorh** [comment]
If you have to support iOS15 and still want to use WhisperKit, you may modify the availability annotations similar to #32 but beware of the risks as this is not tested.
