### ISSUE TITLE
Crash when starting whisperKit in MacOS

### ISSUE THREAD

**Issue by xydz** [argmaxinc/WhisperKit#66]
![image](https://github.com/argmaxinc/WhisperKit/assets/80254186/45edba3d-4364-498f-89ee-29d1457760e4)

error message

Could not launch “WhisperAX”
Domain: IDELaunchErrorDomain
Code: 20
Recovery Suggestion: Runningboard has returned error 5. Please check the system logs for the underlying cause of the error.
User Info: {
    DVTErrorCreationDateKey = "2024-03-09 13:07:42 +0000";
    DVTRadarComponentKey = 968756;
    IDERunOperationFailingWorker = IDELaunchServicesLauncher;
}
--
The operation couldn’t be completed. Launch failed.
Domain: RBSRequestErrorDomain
Code: 5
Failure Reason: Launch failed.
--
Launchd job spawn failed
Domain: NSPOSIXErrorDomain
Code: 162
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "Mac15,6";
    "device_osBuild" = "14.3.1 (23D60)";
    "device_platform" = "com.apple.platform.macosx";
    "dvt_coredevice_version" = "355.7.7";
    "dvt_mobiledevice_version" = "1643.60.2";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 22;
    "operation_errorCode" = 20;
    "operation_errorDomain" = IDELaunchErrorDomain;
    "operation_errorWorker" = IDELaunchServicesLauncher;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.macosx";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "macosx14.2";
    "sdk_osVersion" = "14.2";
    "sdk_variant" = macos;
}
--

System Information

macOS Version 14.3.1 (Build 23D60)
Xcode 15.2 (22503) (Build 15C500b)
Timestamp: 2024-03-09T21:07:42+08:00

**Comment by atiorh** [comment]
Hi @xydz, is your device an Apple Silicon device? (M1 or newer)

**Comment by xydz** [comment]
> Hi @xydz, is your device an Apple Silicon device? (M1 or newer)

Apple M3 Pro

**Comment by olivermontes** [comment]
Local error compile Mac M1

> 
required condition is false: format.sampleRate == hwFormat.sampleRate
(
	0   CoreFoundation                      0x000000019a436ccc __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000199f1e788 objc_exception_throw + 60
	2   CoreFoundation                      0x000000019a45c7f4 -[NSException description] + 0
	3   AVFAudio                            0x00000001f4510260 _Z19AVAE_RaiseExceptionP8NSStringz + 52
	4   AVFAudio                            0x00000001f45d89e8 _ZN17AVAudioIONodeImpl15SetOutputFormatEmP13AVAudioFormat + 1160
	5   AVFAudio                            0x00000001f4533444 _ZN17AUGraphNodeBaseV318CreateRecordingTapEmjP13AVAudioFormatU13block_pointerFvP16AVAudioPCMBufferP11AVAudioTimeE + 892
	6   AVFAudio                            0x00000001f45cbcac -[AVAudioNode installTapOnBus:bufferSize:format:block:] + 1480
	7   WhisperAX                           0x000000010427a804 $s10WhisperKit14AudioProcessorC11setupEngine13inputDeviceIDSo07AVAudioF0Cs6UInt32VSg_tKF + 1244
	8   WhisperAX                           0x00000001042793e0 $s10WhisperKit14AudioProcessorC18startRecordingLive13inputDeviceID8callbackys6UInt32VSg_ySaySfGcSgtKF + 328
	9   WhisperAX                           0x0000000104279258 $s10WhisperKit14AudioProcessorCAA0C10ProcessingA2aDP18startRecordingLive13inputDeviceID8callbackys6UInt32VSg_ySaySfGcSgtKFTW + 56
	10  WhisperAX                           0x0000000104226504 $s9WhisperAX11ContentViewV14startRecordingyySbFyyYaYbcfU_TY2_ + 1188
	11  WhisperAX                           0x00000001042400d5 $s9WhisperAX11ContentViewV14startRecordingyySbFyyYaYbcfU_TATQ0_ + 1
	12  WhisperAX                           0x000000010424941d $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTQ0_ + 1
	13  WhisperAX                           0x000000010424ac71 $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRTATQ0_ + 1
	14  libswift_Concurrency.dylib          0x00000002609d70f9 _ZL23completeTaskWithClosurePN5swift12AsyncContextEPNS_10SwiftErrorE + 1
)

**Comment by xydz** [comment]
> @xydz Did you try restarting xcode, deleting derived data, and cleaning the build folder? Unable to reproduce this

I will log in to Apple Developer again and change the appid.
Special thanks
