### ISSUE TITLE
Support with older swift version

### ISSUE THREAD

**Issue by GameDeva** [argmaxinc/WhisperKit#67]
I have problem being able to develop and run with this sadly. 

I am running a AMD cpu windows 11 pc. I am using vmware to get MacOS, however I am not able to run any MacOS version after 12, due to amd cpu not supporting this. This in turn means that I cannot run the later versions of xcode that support swift 5.9. 

Would you ever considering backporting some of this functionality for previous versions of swift?

**Comment by atiorh** [comment]
Hi @GameDeva, this project only supports Apple Silicon devices. It might still work on pre-Apple Silicon devices but we made the decision not to test or support such devices as of today. Hope this helps.

**Comment by GameDeva** [comment]
Thank you!
