### ISSUE TITLE
Some timing tokens are included in word timestamps

### ISSUE THREAD

**Issue by finnvoor** [argmaxinc/WhisperKit#82]
When filtering out special tokens in addWordTimestamps, word timings that contain a timing token followed by a hyphen aren't filtered out correctly. `WordTiming.tokens` correctly contains just `[532]`, but `WordTiming.word` is `"<|0.00|> -"`. This seems to occur most when multiple people are talking over each other in a recording, I guess it's Whisper's way of trying to label speakers.

**Comment by ZachNagengast** [comment]
This seems like a bug in the token filtering, I will look into this, and if you have any audio files that replicate it that will be helpful as well!

**Comment by finnvoor** [comment]
Here's an example that has some `"<|0.00|> ["` words at 0.0, 29.6, 43.02, 45.6, 367.6, and 397.6. Transcribed using `base.en`, `skipSpecialTokens: true, wordTimestamps: true`.

[Detail_20240327143246.m4a.zip](https://github.com/argmaxinc/WhisperKit/files/14780423/Detail_20240327143246.m4a.zip)

**Comment by ZachNagengast** [comment]
Interesting, I'm able to replicate this, thanks! Also a great example for testing in general 👍
