### ISSUE TITLE
Guard against exceeding the maximum TextDecoder token sequence length for non-streaming mode

### ISSUE THREAD

**Issue by atiorh** [argmaxinc/WhisperKit#89]
Guard against exceeding the maximum TextDecoder token sequence length for non-streaming mode. Long and fast enough speech within a 30-second window occasionally requires more tokens than maximum allowed in Whisper (448 total count, 445 excluding special task tokens)

**Comment by ZachNagengast** [comment]
Closing based on this issue https://github.com/argmaxinc/WhisperKit/issues/63, can reopen either if it shows up again
