### ISSUE TITLE
Support for MacOS 13.0

### ISSUE THREAD

**Issue by kchro3** [argmaxinc/WhisperKit#9]
Hi folks, just wanted to check in and ask what would be entailed in adding support for older mac versions, such as 13.0?

**Comment by atiorh** [comment]
float16 models (all except `_*MB` suffixed models) should be okay to run on macOS 13 but we don't yet have the infrastructure to test on older macOS versions. Quantized models require macOS 14 for proper memory reduction and acceleration. Our internal testing infrastructure is not yet equipped to handle older OS versions but we are actively thinking about this.

If macOS 13 becomes a productionization blocker for a few projects, we will spend more time on thinking about this. In the meantime, do you mind modifying the availability annotations to include macOS 13 in your fork and letting us know how your tests go?

**Comment by finnvoor** [comment]
@atiorh Wondering the same thing about iOS 16 support, I did a find and replace on the availability attributes from 17->16 and it seems to still build fine, but I'm assuming there's similar requirements for quantized models and iOS 17.

We currently support captions in iOS 16/macOS 12.3 in [Detail](https://detail.co), so it would be nice to continue to support these versions if we switch to WhisperKit, but not a hard requirement.

**Comment by atiorh** [comment]
Implemented in #40
