### ISSUE TITLE
Crash on Intel Mac

### ISSUE THREAD

**Issue by xhan** [argmaxinc/WhisperKit#92]
Logs on Load model:

> [WhisperKit] Loading feature extractor
MPSGraph doesn't support padded tensors on Intel macs. @ ValidateTensorAndInitializeMTLBuffer
E5RT: MPSGraph doesn't support padded tensors on Intel macs. (11)
MPSGraph doesn't support padded tensors on Intel macs. @ ValidateTensorAndInitializeMTLBuffer
E5RT: MPSGraph doesn't support padded tensors on Intel macs. (11)
[WhisperKit] Loaded feature extractor
[WhisperKit] Loading audio encoder
[WhisperKit] Loaded audio encoder
[WhisperKit] Loading text decoder
[WhisperKit] Loaded text decoder
[WhisperKit] Loading tokenizer for base
BOOL _NSPersistentUIDeleteItemAtFileURL(NSURL *const __strong) Failed to stat item: file:///Users/xhan/Library/Containers/com.xhan.argmax.whisperkit.WhisperAX/Data/Library/Saved%20Application%20State/com.xhan.argmax.whisperkit.WhisperAX.savedState/restorecount.plist
[WhisperKit] Loaded tokenizer
[WhisperKit] Loaded models for whisper size: base
throwing -10877
throwing -10877
throwing -10877
throwing -10877
[WhisperKit] Successfully set input device.

Crash at line 86 of `Utils.swift`
`let typedPointer = pointer.bindMemory(to: FloatType.self, capacity: count)`

> ForEach<ArraySlice<(offset: Int, element: Float)>, Float, ModifiedContent<ModifiedContent<ZStack<ModifiedContent<RoundedRectangle, _FrameLayout>>, _FlexFrameLayout>, _BackgroundStyleModifier<Color>>>: the ID 0.0 occurs multiple times within the collection, this will give undefined results!

**Comment by atiorh** [comment]
Intel Macs are currently unsupported. Supported devices:
- Mac and iPad: M1 and newer
- iPhone: iPhone 12 and newer
- Watch: Ultra 2/S9 and newer

**Comment by atiorh** [comment]
Implementing a fallback solution for unsupported devices is on the roadmap. I will keep this issue posted with progress.
