### ISSUE TITLE
temperatureStart is unused

### ISSUE THREAD

**Issue by cgfarmer4** [argmaxinc/WhisperKit#93]
I dont see `temperatureStart` being used anywhere in the repo, however it exists in the settings view. Is this intentional? Shouldnt it be passed to `DecodingOptions`? Same for `fallbackCount`.

**Comment by ZachNagengast** [comment]
You're right, this is an oversight! Will get this in the next release 👍

**Comment by cgfarmer4** [comment]
Cool, I can PR later this week too.
