### ISSUE TITLE
Issue with languages other than English

### ISSUE THREAD

**Issue by miguel-arrf** [argmaxinc/WhisperKit#98]
Hi!

I've been playing with the sample app, and, at least for Spanish and Portuguese, regardless of the task (either Transcribe or Translate), the output is being translated.

The `whisper-large-v3-turbo 954MB` model is the only one that doesn't translate automatically (it happens with all other v3 large models). Is this expected? 

Thank you :)

**Comment by ZachNagengast** [comment]
@miguel-arrf thanks for the report, which models did you try? Depending on the source audio, the smaller models can have a tough time with transcription. To get Spanish text out, you'll definitely want to use transcribe with the language set to Spanish. If you have a sample audio file we can take a look as well.

**Comment by atiorh** [comment]
@miguel-arrf  Could you also report the results with `Settings > Cache prefill` disabled?

**Comment by ArchieGoodwin** [comment]
I see the same behavior with distil-whisper_distil-large-v3_594MB model. If set language to nil then it translates to English even if task is set to transcribe

**Comment by ArchieGoodwin** [comment]
And I have tried with Cache profile false. The same result. If languageCode is set then all is working as expected. But I wanted to use automatics language detection instead of setting language manually

**Comment by ArchieGoodwin** [comment]
I was wrong, even if set language to specific language distil-whisper_distil-large-v3_594MB return English translation. For Transcribe task

**Comment by ZachNagengast** [comment]
Would you mind providing some implementation details such as the code being used? And ideally verbose logs of a case where you see this happening?

**Comment by ZachNagengast** [comment]
@miguel-arrf sorry for the delay, I can see from this log that the prefill prompt is not being used, so it just is trying to transcribe into english by default. In the app, make sure this is enabled, and in CLI it is `--use-prefill-prompt`

![CleanShot 2024-04-08 at 11 56 56@2x](https://github.com/argmaxinc/WhisperKit/assets/1981179/c309b93d-c7b4-4ef1-a5d2-d5d2f80e91c5)

In addition to that the distil model you're using is actually not trained to be multilingual, so it will always output english text.

**Comment by atiorh** [comment]
> In addition to that the distil model you're using is actually not trained to be multilingual, 
Emphasis on this: Definitely use a `large-v3` or `small` variant for non-English applications.

**Comment by ArchieGoodwin** [comment]
I see, make sense. Thank you

**Comment by ArchieGoodwin** [comment]
But one question still. Is automatic language detect works for example with large-v3 or small models? I can't make it work

**Comment by ZachNagengast** [comment]
@ArchieGoodwin I've added a new decoding option in #114 called `detectLanguage` which will enforce checking the language regardless of `usePrefillPrompt` settings. You may also use it on its own to do a single forward pass and return the language with code like this:

```swift
        let whisperKit = try await WhisperKit(
            modelFolder: tinyModelPath(),
            verbose: true,
            logLevel: .debug
        )

        let audioFilePath = try XCTUnwrap(
            Bundle.module.path(forResource: "ja_test_clip", ofType: "wav"),
            "Audio file not found"
        )

        // To detect language only, set `sampleLength` to 1 and no prefill prompt
        let optionsDetectOnly = DecodingOptions(task: .transcribe, temperatureFallbackCount: 0, sampleLength: 1, detectLanguage: true)

        let result = try await XCTUnwrapAsync(
            await whisperKit.transcribe(audioPath: audioFilePath, decodeOptions: optionsDetectOnly),
            "Failed to transcribe"
        )

       print(result.language)
```

**Comment by ArchieGoodwin** [comment]
This works! Thank you @ZachNagengast
